# -*- coding: utf-8 -*-
from . import sa_qr_mixin
from . import sa_transfer_tax
from . import sa_misc_charge
from . import sa_payment_plan
from . import sa_property_project
from . import sa_property_dealer
from . import sa_property
from . import sa_property_media
from . import sa_property_service
from . import sa_property_booking
from . import sa_property_installment
from . import sa_property_transfer
from . import sa_dealer_allocation
from . import sa_lead_source
from . import crm_lead
from . import sa_property_dashboard
from . import sa_property_dashboard_config
from . import res_config_settings
from . import res_partner
from . import account_move
